### Filtering Array (Boolean Indexing)

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 15, 20, 25, 30])

In [3]:
arr

array([10, 15, 20, 25, 30])

In [4]:
l = [True, False, True, True, False]
l

[True, False, True, True, False]

In [6]:
arr[l]

array([10, 20, 25])

In [7]:
arr

array([10, 15, 20, 25, 30])

In [8]:
l2 = (arr%2 == 0)
l2

array([ True, False,  True, False,  True])

In [9]:
arr[l2]

array([10, 20, 30])

In [10]:
arr[arr%2 == 0]

array([10, 20, 30])

In [11]:
age = np.array([42, 18, 22, 13, 16])

In [12]:
age

array([42, 18, 22, 13, 16])

In [13]:
age[age > 18]

array([42, 22])

In [14]:
age[age == 22]

array([22])

In [15]:
a2 = np.array([[3, 5, 7], [1, 2, 9], [6, 4, 2]])
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [16]:
l1 = [True, False, True]

In [17]:
a2[l1]

array([[3, 5, 7],
       [6, 4, 2]])

### Boolean Mask (Masing Array)

In [18]:
arr

array([10, 15, 20, 25, 30])

In [19]:
l

[True, False, True, True, False]

In [20]:
np.ma.array(arr, mask=l)    # arr[l]

masked_array(data=[--, 15, --, --, 30],
             mask=[ True, False,  True,  True, False],
       fill_value=999999)

In [21]:
odd_numbers = np.ma.array(arr, mask=arr%2==0)
print(odd_numbers)

[-- 15 -- 25 --]


### Reshaping Array

In [22]:
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [23]:
a2.flatten()    # Converts Multi-dimensional array into 1D array

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [24]:
a2.reshape(-1)    # Converts Multi-dimensional array into 1D array

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [25]:
a2.ravel()    # Converts Multi-dimensional array into 1D array

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [26]:
a1d = np.arange(12)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
a1d.reshape(4, 3)   # Converts 1D array into Multi-dimensoinal array e.g., 1D to 2D array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
a1d.reshape(2, -1)   # -1 means automatically decides the possible dimension

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
a1d.reshape(-1, 6)   # -1 means automatically decides the possible dimension

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [30]:
a1d.reshape(-1, 3)   # -1 means automatically decides the possible dimension

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
a1d.reshape(2, 3, 2)   # Converts 1D array into Multi-dimensoinal array e.g., 1D to 3D array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

### Broadcasting of Array

###### Broadcasting is a powerful mechanism in NumPy that allows array operations between arrays of different shapes without copying data.

###### In simple terms: Broadcasting allows you to automatically expand smaller arrays to match the shape of larger arrays during operations like addition, multiplication, etc.

---

###### **🧠 Why is Broadcasting Needed?**
###### When doing arithmetic on arrays, NumPy performs the operation element-wise. But what if the shapes don’t match?

###### Instead of throwing an error, broadcasting stretches the smaller array to fit the shape of the larger one — virtually (no memory copy!).

###### **📏 Types of Broadcasting**

###### 1. Scalar Broadcasting
###### 2. Vector Broadcasting
###### 3. Matrix Broadcasting

---

##### 🔸 1. Scalar Broadcasting

###### A scalar is a single number. When you operate a scalar with an array, the scalar is broadcast to the shape of the array.

In [32]:
arr

array([10, 15, 20, 25, 30])

In [34]:
# Scaler => One elemnet array
s1 = [3]
s2 = 5
s3 = np.array([6])

In [35]:
arr + s2

array([15, 20, 25, 30, 35])

In [36]:
arr + s1

array([13, 18, 23, 28, 33])

In [37]:
arr + 8

array([18, 23, 28, 33, 38])

In [38]:
arr + s3

array([16, 21, 26, 31, 36])

---

##### 🔸 2. Vector Broadcasting

###### (a) Row Vector Broadcasting (1D)
###### (b) Column Vector Broadcasting

---

###### **(a) Row Vector Broadcasting (1D)**
###### A 1D array can be broadcast across each row of a 2D array if shapes are compatible.

In [40]:
a1 = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

a2 = np.array([10, 20, 30])  # shape (3,)

print(a1 + a2)

# a1.shape = (2, 3)
# a2.shape = (3,) → broadcast to (2, 3) ➡️ Added to each row

[[11 22 33]
 [14 25 36]]


###### **(b) Column Vector Broadcasting**
###### Use reshape() to turn a 1D array into a column vector (n x 1) and broadcast it column-wise.

In [41]:
a1 = np.array([[1, 2, 3],
              [4, 5, 6]])

# a2 = np.array([[10], [20]])
a2 = np.array([10, 20]).reshape(-1, 1)

print(a1 + a2)

# a2.shape = (2, 1) → added down each row

[[11 12 13]
 [24 25 26]]


---

##### 🔸 3. Matrix Broadcasting

###### Broadcasting happens between matrices of different shapes if they satisfy broadcasting rules.

###### **✅ Rules:**
###### Compare shapes from right to left

###### Dimensions are compatible if:
- ###### Same, or
- ###### One is 1

In [43]:
a1 = np.array([[1], [2]])
a2 = np.array([[10, 20, 30]])

print(a1)
print()
print(a2)
print()

a3 = a1 + a2
print(a3)

# a1 → (2, 1) → expanded across columns
# a2 → (1, 3) → expanded across rows
# Result shape → (2, 3)

[[1]
 [2]]

[[10 20 30]]

[[11 21 31]
 [12 22 32]]


In [45]:
# ❌ Incompatible Shapes Example:

a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([1, 2, 3])

print(a1)
print()
print(a2)

print(a1 + a2)

# ValueError: operands could not be broadcast together with shapes (2,2) (3,)
# Shapes (2,2) and (3,) cannot match by any rule.

[[1 2]
 [3 4]]

[1 2 3]


ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [47]:
# ❌ Incompatible Shapes Example:

a1 = np.array([[2, 5, 4, 1], [6, 5, 8, 9], [3, 2, 5, 4]])
a2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [3, 2, 1, 4], [7, 8, 5, 6]])

print(a1)
print()
print(a2)
print()

a3 = a1 + a2

print(a3)

[[2 5 4 1]
 [6 5 8 9]
 [3 2 5 4]]

[[1 2 3 4]
 [4 5 6 7]
 [3 2 1 4]
 [7 8 5 6]]



ValueError: operands could not be broadcast together with shapes (3,4) (4,4) 